apiVersion: v1
data:
  MYSQL_DATABASE: wordpress
  MYSQL_PASSWORD: wppassword
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_USER: wpuser
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: db-env
  name: env
