apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wordpress
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose.exe convert
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: wordpress
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env
          image: wordpress:6.5.3-php8.2-apache
          name: wordpress
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
